name: table_provider
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - certifi=2022.12.7
  - comm=0.1.3
  - decorator=5.1.1
  - executing=1.2.0
  - importlib_metadata=6.5.0
  - jedi=0.18.2
  - jupyter_client=8.2.0
  - matplotlib-inline=0.1.6
  - nest-asyncio=1.5.6
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.38
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python-dateutil=2.8.2
  - python_abi=3.10
  - setuptools=65.6.3
  - six=1.16.0
  - stack_data=0.6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - wcwidth=0.2.6
  - zipp=3.15.0
  - debugpy
  - bzip2
  - ca-certificates
  - libcxx
  - libffi
  - libsodium
  - openssl
  - pip
  - psutil
  - python
  - pyzmq
  - sqlite
  - tk
  - tornado
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - async-generator==1.10
      - async-timeout==4.0.2
      - attrs==22.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blis==0.7.9
      - bs4==0.0.1
      - build==0.10.0
      - cachecontrol==0.12.11
      - cachetools==5.3.1
      - catalogue==2.0.8
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - cleo==2.0.1
      - click==8.1.3
      - contourpy==1.0.7
      - crashtest==0.4.1
      - cssselect==1.2.0
      - cycler==0.11.0
      - cymem==2.0.7
      - dataclasses-json==0.5.7
      - datasets==2.11.0
      - datedelta==1.4
      - defusedxml==0.7.1
      - dill==0.3.6
      - diskcache==5.6.1
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - dulwich==0.21.3
      - emoji==1.7.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.1
      - faiss-cpu==1.7.4
      - fake-useragent==1.1.3
      - fastjsonschema==2.16.3
      - filelock==3.11.0
      - fonttools==4.39.3
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-api-core==2.11.1
      - google-api-python-client==2.93.0
      - google-auth==2.22.0
      - google-auth-httplib2==0.1.0
      - googleapis-common-protos==1.59.1
      - googlesearch-python==1.2.3
      - gpt4all==1.0.5
      - grapheme==0.6.0
      - greenlet==2.0.2
      - h11==0.14.0
      - html5lib==1.1
      - httplib2==0.22.0
      - huggingface-hub==0.13.4
      - idna==3.4
      - importlib-metadata==6.3.0
      - installer==0.7.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jaraco-classes==3.2.3
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonlines==3.1.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - keyring==23.13.1
      - kiwisolver==1.4.4
      - llama-cpp-python==0.1.72
      - lockfile==0.12.2
      - lxml==4.9.2
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mistune==2.0.5
      - more-itertools==9.1.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6
      - torch==2.4.1
      - torch_scatter==2.1.2
      - recognizers-text==1.0.2a2
      - recognizers-text-choice==1.0.2a2
      - recognizers-text-date-time==1.0.2a2
      - recognizers-text-number==1.0.2a2
      - recognizers-text-number-with-unit==1.0.2a2
      - recognizers-text-sequence==1.0.2a2
      - recognizers-text-suite==1.0.2a2
      - openapi-schema-pydantic==1.2.4
      - pydantic==2.9.2
      - pydantic-settings==2.5.2
      - pydantic_core==2.23.4
      - transformers
      - openpyxl
      - wandb
      - scikit-learn
      - openai
      - tiktoken
      - tabulate
      - nltk
      - wikipedia
      - wikiextractor
      - flask
      - flask_restful
      - azure-identity
      - pandas
      - numpy
      - matplotlib
      - langchain
      - langchain-community